name = "barber-shop-website-design"
compatibility_date = "2023-10-26"

# Make sure this file is in your project's root directory.
# You can delete the other wrangler.toml file.

[[d1_databases]]
binding = "DB" # This is the name you'll use in your Worker code to access the database.
database_name = "barbershop-db" # <-- PASTE YOUR DATABASE NAME HERE
database_id = "ca51dc60-bde4-4bbd-bedf-fdc5ddfd56a3" # <-- PASTE YOUR DATABASE ID HERE

# This links the D1 binding to your Pages Functions

